Importer: add option to import product variations
shuup/shuup pull request #2287
Opened 2020-10-14 10:55 UTC by tulimaki

- Add option to import product variations
- Improve handle stock to get supplier by supplier name and set the supplier stock managed and update the module identifier.
- Improve handle stock to set the logical count to desired quantity instead adding new stock for the amount. This should help sellers to keep their product stock value correct.

2020-10-14 20:00 UTC, chessbr requested changes
Will this work for vendor users?

2020-10-15 10:00 UTC, tulimaki commented on shuup/default_importer/importers/product.py
> +            sess.log_messages.append(msg)
It shouldn't create variation variables if there is no valid variations. Also all the rows in the import are already atomic.

2020-10-15 10:00 UTC, tulimaki commented
We should add that handler to the vendor product import after this is released. And yes this would then also work for vendor users.

2020-10-15 12:22 UTC, chessbr approved these changes

2020-10-15 12:22 UTC, merged